{
 "title": "Kube-apiserver",
 "time": { "from": "2024-07-26T07:10:59.159Z", "to": "2024-07-26T14:41:46.116Z" },
 "panels": [
  {
   "title": "Kube-apiserver QPS",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Common API resources",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "containers"
    },
    { "expr": "sum(kube_pod_status_phase)", "legendFormat": "pods" },
    { "expr": "sum(kube_service_info)", "legendFormat": "services" },
    { "expr": "sum(kube_endpoint_info)", "legendFormat": "endpoints" },
    { "expr": "sum(kube_ingress_info)", "legendFormat": "ingresses" },
    {
     "expr": "sum(sum(kube_deployment_status_replicas_available) by (deployment))\n",
     "legendFormat": "deployments"
    },
    {
     "expr": "sum(sum(kube_statefulset_status_replicas_ready) by (statefulset)\n)",
     "legendFormat": "statefulsets"
    },
    {
     "expr": "sum(sum(kube_daemonset_status_number_ready) by (daemonset))\n",
     "legendFormat": "daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info)",
     "legendFormat": "PVC"
    },
    { "expr": "sum(kube_configmap_info)", "legendFormat": "configmaps" },
    { "expr": "sum(kube_secret_info)", "legendFormat": "secrets" },
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "nodes"
    },
    { "expr": "count(kube_namespace_created)", "legendFormat": "namespaces" },
    {
     "expr": "count(kube_networkpolicy_created)",
     "legendFormat": "netpols"
    }
   ]
  },
  {
   "title": "Deprecated API calls",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_requested_deprecated_apis",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-apiservers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability 90days",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"kubernetes-apiservers\"}[90d]) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability 30days",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"kubernetes-apiservers\"}[30d]) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability 7days",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"kubernetes-apiservers\"}[7d]) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube-apiserver memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kubernetes-apiservers\"}",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Kube-apiserver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kubernetes-apiservers\"}[2m])",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Kube-apiserver API resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apiserver_storage_objects) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate by VERB against kube-apiserver",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (verb) (\n  rate(apiserver_request_total{job=\"kubernetes-apiservers\"}[2m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total API Request Duration Sum by Verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (verb) (\n  rate(apiserver_request_duration_seconds_sum{job=\"kubernetes-apiservers\", verb!=\"WATCH\"}[4m])\n)\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube-apiserver Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (verb) (\n  rate(apiserver_request_duration_seconds_sum{job=\"kubernetes-apiservers\", verb!=\"WATCH\"}[4m])\n) / \nsum by (verb) (\n  rate(apiserver_request_duration_seconds_count{job=\"kubernetes-apiservers\", verb!=\"WATCH\"}[4m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube-apiserver Average Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_response_sizes_sum{job=\"kubernetes-apiservers\"}[2m])) / sum(rate(apiserver_response_sizes_count{job=\"kubernetes-apiservers\"}[2m]))\n",
     "legendFormat": "response size"
    }
   ]
  },
  {
   "title": "Kube-apiserver Median Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_response_sizes_bucket{job=\"kubernetes-apiservers\"}[2m])) by (le))\n",
     "legendFormat": "median response size"
    }
   ]
  },
  {
   "title": "Kube-apiserver Top 1% Response Size (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_response_sizes_bucket{job=\"kubernetes-apiservers\"}[2m])) by (le))\n",
     "legendFormat": "99th percentile response size"
    }
   ]
  },
  {
   "title": "Long running requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (verb) (\n  apiserver_longrunning_requests{job=\"kubernetes-apiservers\", verb!=\"WATCH\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(\n  apiserver_current_inflight_requests{job=\"kubernetes-apiservers\"}\n)\n",
     "legendFormat": "inflight requests"
    }
   ]
  },
  {
   "title": "ETCD request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (\n  rate(etcd_request_duration_seconds_count{job=\"kubernetes-apiservers\"}[2m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (\n  rate(etcd_request_duration_seconds_sum{job=\"kubernetes-apiservers\"}[5m])\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube-apiserver open FileDescriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"kubernetes-apiservers\"}",
     "legendFormat": "file descriptor"
    }
   ]
  },
  {
   "title": "Kube-apiserver go rutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"kubernetes-apiservers\"}",
     "legendFormat": "go rutines"
    }
   ]
  }
 ]
}